### ISSUE TITLE
大佬 我现在有个问题 能不能讨论下

### ISSUE THREAD

**Issue by fengahan** [krwu/spiraldocs#9]
class HomeController
{
    public static $count=1;
    use PrototypeTrait;

    /**
     * @return string
     */
    public function index(): string
    {
        $data=[];
        self::$count++;
        echo self::$count;
        return $this->views->render('home.dark.php',$data);
    }
}
这个count 的数值会在多个进程里面混肴 怎么解决

**Comment by krwu** [comment]
抱歉，最近比较忙，现在才来回复你。

Spiral 由于是由 Golang 的应用服务器调度的任务进程，因此你可以理解为每个 http workload 都是独立的一个环境。因此以往习惯的“单例模式”、“类属性（静态属性）”等，在进程间是无效的。但是如果使用单进程的话（即教程中的开发模式）那么 spiral 会在每个请求时重启 http 工作进程。因此也是无效的。所以 Spiral 对内存中的“缓存”的定义就是随时可丢，随时可恢复，不能作为持久化或者半持久化的数据使用（比如全局计数器）。

spiral 开发团队目前已经计划在 2.5 版本实现 golang 层面的 KeyValue 服务，从而实现进程间共享内存数据。

就目前而言，你只能通过 Redis 一类的外部缓存来实现。

参见我之前遇到跟你类似的问题时提的这个 issue: spiral/framework/issues/263

**Comment by fengahan** [comment]
没事的 我在想 如果这样误用会造成比较严重的问题

**Comment by krwu** [comment]
> 没事的 我在想 如果这样误用会造成比较严重的问题

是的，特别是文档里多处提到了 “Singleton”。这个跟传统 PHP 甚至 Swoole 的机制都不同。等于目前 Spiral 没有全局共享内存。
